# Generated by Django 4.2 on 2023-04-06 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20230406_1222'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='old_id',
            field=models.TextField(blank=True, null=True),
        ),
    ]
