# Generated by Django 4.2 on 2023-04-06 19:02

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_card_old_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='type',
            field=models.TextField(choices=[('Habit', 'habit'), ('Self Check-In', 'check'), ('Miscellaneous', 'misc'), ('Miscellaneous', 'other'), ('Miscellaneous', 'standard'), ('Book', 'book'), ('Article', 'article'), ('Learning', 'learn'), ('Project', 'project')]),
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('score', models.IntegerField(default=0)),
                ('type', models.TextField(choices=[('Habit', 'habit'), ('Self Check-In', 'check'), ('Miscellaneous', 'misc'), ('Miscellaneous', 'other'), ('Miscellaneous', 'standard'), ('Book', 'book'), ('Article', 'article'), ('Learning', 'learn'), ('Project', 'project')])),
                ('old_id', models.TextField(blank=True, null=True)),
                ('input_type', models.IntegerField()),
                ('skip_note', models.TextField(blank=True, null=True)),
                ('card_front', models.TextField(blank=True, null=True)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.card')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.profile')),
            ],
        ),
    ]
