# Generated by Django 4.2 on 2023-04-06 19:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_card_type_log'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='card',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.card'),
        ),
    ]
