# Generated by Django 4.2 on 2023-04-06 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_log_card'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='type',
            field=models.TextField(blank=True, choices=[('Habit', 'habit'), ('Self Check-In', 'check'), ('Miscellaneous', 'misc'), ('Miscellaneous', 'other'), ('Miscellaneous', 'standard'), ('Book', 'book'), ('Article', 'article'), ('Learning', 'learn'), ('Project', 'project')], null=True),
        ),
    ]
