# Generated by Django 4.2 on 2023-04-07 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_log_input_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='type',
            field=models.TextField(choices=[('Habit', 'habit'), ('Self Check-In', 'check'), ('Miscellaneous', 'misc'), ('Miscellaneous', 'other'), ('Miscellaneous', 'standard'), ('Book', 'book'), ('Book', 'readingList'), ('Article', 'article'), ('Article', 'articleList'), ('Learning', 'learn'), ('Project', 'project')]),
        ),
        migrations.AlterField(
            model_name='log',
            name='input_type',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='log',
            name='type',
            field=models.TextField(blank=True, choices=[('Habit', 'habit'), ('Self Check-In', 'check'), ('Miscellaneous', 'misc'), ('Miscellaneous', 'other'), ('Miscellaneous', 'standard'), ('Book', 'book'), ('Book', 'readingList'), ('Article', 'article'), ('Article', 'articleList'), ('Learning', 'learn'), ('Project', 'project')], null=True),
        ),
    ]
