# Generated by Django 4.2 on 2023-04-11 13:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0009_alter_card_type_alter_log_input_type_alter_log_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='log',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='profile',
        ),
        migrations.AddField(
            model_name='card',
            name='child_cards',
            field=models.ManyToManyField(blank=True, related_name='parent_cards', to='main.card'),
        ),
        migrations.AddField(
            model_name='card',
            name='connected_cards',
            field=models.ManyToManyField(blank=True, related_name='connected_cards', to='main.card'),
        ),
        migrations.AddField(
            model_name='card',
            name='old_user_id',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='card',
            name='parent_cards',
            field=models.ManyToManyField(blank=True, related_name='children_cards', to='main.card'),
        ),
        migrations.AddField(
            model_name='card',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='log',
            name='old_user_id',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='log',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tag',
            name='old_user_id',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tag',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
