# Generated by Django 4.2 on 2023-04-11 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_remove_card_profile_remove_log_profile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='child_cards',
            field=models.ManyToManyField(blank=True, to='main.card'),
        ),
        migrations.AlterField(
            model_name='card',
            name='connected_cards',
            field=models.ManyToManyField(blank=True, to='main.card'),
        ),
        migrations.AlterField(
            model_name='card',
            name='parent_cards',
            field=models.ManyToManyField(blank=True, to='main.card'),
        ),
    ]
